name: Release NodeJS Library

inputs:
  NODE_VERSION:
    description: NodeJS Version
    required: true

runs:
  using: composite
  steps:
    - name: echo Inputs and Outputs
      run: echo "INPUT_NODE_VERSION=${{ inputs.NODE_VERSION }}"
      shell: bash
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.NODE_VERSION }}
    - name: Install and Build
      run: |
        npm ci 
        npm run build --if-present
      shell: bash
    - name: Run tests
      run: npm test
      shell: bash